CREATE TABLE if not exists categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('RECEITA', 'DESPESA'))
);

INSERT INTO categories (nome, tipo)
VALUES
    ('Salário', 'RECEITA'),
    ('Renda Extra (Freela)', 'RECEITA'),
    ('Investimentos', 'RECEITA'),
    ('Presentes', 'RECEITA'),
    ('Outras Receitas', 'RECEITA'),


    ('Aluguel', 'DESPESA'),
    ('Financiamento', 'DESPESA'),
    ('Condomínio', 'DESPESA'),
    ('Água', 'DESPESA'),
    ('Energia Elétrica', 'DESPESA'),
    ('Internet / TV / Telefone', 'DESPESA'),
    ('Casa', 'DESPESA'),
    ('Supermercado', 'DESPESA'),
    ('Restaurantes / Delivery', 'DESPESA'),
    ('Veículo', 'DESPESA'),
    ('Transporte', 'DESPESA'),
    ('Saúde', 'DESPESA'),
    ('Cuidados Pessoais', 'DESPESA'),
    ('Academia / Esportes', 'DESPESA'),
    ('Lazer e Entretenimento', 'DESPESA'),
    ('Compras', 'DESPESA'),
    ('Assinaturas', 'DESPESA'),
    ('Investimentos (Aportes)', 'DESPESA'),
    ('Presentes / Doações', 'DESPESA'),
    ('Educação', 'DESPESA'),
    ('Outras Despesas', 'DESPESA');

